### ISSUE TITLE
testsuite out of memory?

### ISSUE THREAD

**Issue by juhp** [emilypi/base64#31]
Recent Stackage builds have been seeing base64 testsuite getting killed: might be OOM or something related.

```
--  While building package base64-0.4.2.2 (scroll up to its section to see the error) using:
      /var/stackage/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_3.2.1.0_ghc-8.10.3 --builddir=.stack-work/dist/x86_64-
linux/Cabal-3.2.1.0 build lib:base64 test:tasty bench:bench --ghc-options ""
    Process exited with code: ExitFailure (-9) (THIS MAY INDICATE OUT OF MEMORY)
    Logs have been written to: /var/stackage/work/unpack-dir/.stack-work/logs/base64-0.4.2.2.log

    Configuring base64-0.4.2.2...
    Preprocessing library for base64-0.4.2.2..
    Building library for base64-0.4.2.2..
    Preprocessing test suite 'tasty' for base64-0.4.2.2..
    Building test suite 'tasty' for base64-0.4.2.2..
    [2 of 2] Compiling Main [Test.Tasty.QuickCheck changed]
```

**Comment by emilypi** [comment]
Wow that's uh... impressive! A badge off honor! 😂 

I'll see if if i can get the memory usage down. I'm using some typelevel shenanigans to generate test trees at compile time, so i imagine it's a stack size issue if Stackage is running builds with truncated memory to save on compute costs (or simply using small instances).

**Comment by emilypi** [comment]
@juhp Okay, i wrote #32 which speeds up the tests by a large margin. Could you test the changes in 906d51df7f169ae879a4340dd4bb6f7e5875412c on your end to confirm?

**Comment by juhp** [comment]
Thanks a lot, @emilypi - to be honest it is not very practical to test unreleased packages on the Stackage builder, since we only pull from Hackage, but I can try to test manually somehow perhaps.

**Comment by emilypi** [comment]
I have no knowledge of how you run builds for stackage, but I was imagining you could pin the git ref if it uses anything like a `package.yaml`. Is it possible to enter into the instances manually and unpack the reference? I could also just provide a release based on the main branch here that could be used to test...

**Comment by emilypi** [comment]
Any updates on this @juhp?

**Comment by juhp** [comment]
Sorry I didn't really find time yet - and I am not on Stackage "duty" again for a few weeks yet.
TBH I think the easiest for us would be to have a Hackage release and then we can try to re-enable the testsuite in Nightly. I think our Stackage buildserver only has 8GB RAM.
But perhaps I can try locally (on my 16GB laptop) to compare the resource usage - I guess you would see similar results on your end - from your earlier comments it sounds like you probably already fixed the problem. :-)

cc @bergmark (edit sorry) who is on duty this week.

**Comment by juhp** [comment]
I tested 356ae1c locally with cabal and ghc-8.8.4 and with it test/Main.hs seems to compile with <2GB of vmem so it LGTM, thanks.

I think we can revert the testsuite back on in Stackage with a new base64 release.

**Comment by emilypi** [comment]
Great news, thanks @juhp. I've cut a release: https://hackage.haskell.org/package/base64-0.4.2.3

**Comment by juhp** [comment]
Thanks - just noting we will re-enable the testsuite at best effort.
Safest way to ensure it happens is to open a stackage PR. :+1:

**Comment by emilypi** [comment]
Will do thanks @juhp
