### ISSUE TITLE
Big Endian

### ISSUE THREAD

**Issue by lehins** [emilypi/base64#36]
I'd like to point out that there is a bug in ghc <8 .10 that makes this code to not work correctly on Big Endian machines: https://gitlab.haskell.org/ghc/ghc/-/issues/20338

https://github.com/emilypi/base64/blob/d1ea8992832cc553e9071386c083a2795d2fb377/src/Data/ByteString/Base64/Internal/Utils.hs#L155-L165

**Comment by emilypi** [comment]
Thanks for the head's up @lehins. That's disappointing :weary: 

Sounds like I should go back to CPP and import machdeps directly.
