### ISSUE TITLE
Make a release?

### ISSUE THREAD

**Issue by nikita-volkov** [emilypi/base64#40]
To support GHC 9.2

**Comment by simonmichael** [comment]
+1 to this, as I think it will help unblock yesod with GHC 9.2 (cc https://github.com/commercialhaskell/stackage/issues/6486). ~~It does require code changes:~~ [apparently already fixed, just needs a release]

**Comment by simonmichael** [comment]
Thanks! This has made it possible to build yesod with GHC 9.2.
