### ISSUE TITLE
Please make Hackage revision to 0.4.2.4 for GHC 9.8

### ISSUE THREAD

**Issue by tomjaguarpaw** [emilypi/base64#55]
To support GHC 9.8 the following bounds relaxations should be applied as a Hackage revision:

* `base < 4.20`
* `deepseq < 1.6`
* `text < 2.2`
* ~`bytestring < 0.13`~ (not actually required, but would be useful)

(This is blocking [`stan`](https://github.com/kowainik/stan/issues/537) from supporting 9.8)

**Comment by emilypi** [comment]
Have you tested with these bounds on that branch?

**Comment by tomjaguarpaw** [comment]
Yes, I've tested these bounds in two ways.

### `cabal repl` with adjusted bounds

This succeeds, which I believe should be sufficient to show that the bounds bump for the Hackage package is correct:

```
cabal repl \
  -z \
  -b base64 \
  -w ghc-9.8 \
  --allow-newer='base64:base' \
  --allow-newer='base64:deepseq' \
  --allow-newer='base64:text' \
  -b 'base>=4.19.0.0' \
  -b 'deepseq>=1.5' \
  -b 'text>=2.1'
```

### A commit in the `base64` git repo

If you mean have I tested the the 0.4.2.4 branch, well, there isn't one, nor a tag, but checking out `d2c859b` (which seems to be what 0.4.2.4 was cut from) and doing the following works:

```
cabal configure -w ghc-9.8 --enable-tests --allow-newer
cabal freeze
cabal test # succeeds
```

and `cabal.project.freeze` contains

```
% egrep 'any.(base|text|bytestring|deepseq) ' cabal.project.freeze
             any.base ==4.19.0.0,
             any.deepseq ==1.5.0.0,
             any.text ==2.1,
```

So that demonstrates that the bumped bounds work with the state of the git repo at (presumably) 0.4.2.4.

**Comment by emilypi** [comment]
Alright, sounds good thanks for the analysis. I really should probably tag that release 😄

**Comment by emilypi** [comment]
Revised. Thanks @tomjaguarpaw !

**Comment by tomjaguarpaw** [comment]
Thank you!
