### ISSUE TITLE
Get [base64] on Stackage

### ISSUE THREAD

**Issue by Vlix** [emilypi/base64#6]
Is there a plan to get this package onto Stackage?

It'd be great if it could be before the next LTS.

**Comment by emilypi** [comment]
That's up to the stackage people. I submitted it for upload weeks ago with https://github.com/commercialhaskell/stackage/pull/5056

**Comment by Vlix** [comment]
Ah, it's in the nightly builds! It'll be added in LTS-15 then. Great!

I couldn't find `base64` on hackage either, since the search function never found it. Just making a correct URL to it does work, so it IS on there. Just like searching on stackage doesn't find it, unless you manually go to the correct URL.

I wonder why that is :/

**Comment by emilypi** [comment]
Unsure! I have a link to it through the `hackage` badge in the README of this project if you ever need a quick link. Alternatively, here: https://hackage.haskell.org/package/base64
